### ISSUE TITLE
how to get channel numbers?

### ISSUE THREAD

**Issue by unknwon00** [Debaucus/KickChatConnection#1]
how do i find the channel numbers for the streamers i watch?

**Comment by Coriana** [comment]
open up the F12 dev tools, look at the Network tab.
Go to a page with chat, then find a request to chat-messages. 
chatroom id is at the beginning under payload.
![image](https://user-images.githubusercontent.com/48957445/227711915-ad4de78a-2f94-4c8e-b537-05766080a944.png)
